### PR TITLE
Corrected discrepancy between npm module naming and ambient module de…

### PR DESCRIPTION
**Pull request by thor-schueler**
…claration naming.

Should resolve isssue #225 

@darewreck54, @stewx, @ali-hamud

### CODE REVIEW

**Comment by ali-hamud** [comment]
Hi @thor-schueler 
Your changes are ok. I added them to code. I didn't take your code to avoid different leading spaces

**Comment by thor-schueler** [comment]
Yeah, sorry about the spaces. Not sure what happened there, but I suspect it is my VSCode settings. I'll confirm the fix later today and close out the pull...

**Comment by thor-schueler** [comment]
I have confirmed that this resolved the issue. Thanks all!

**Comment by stewx** [comment]
Works for me now.

**Pull request closed without merging**
