### PR TITLE
Fix bug when multiple embeds have no or duplicated element id

### PR DESCRIPTION
**Pull request by oceantume**
This bug caused multiple embeds to break when the elements had no id or
duplicated ids. This broke event handling and some interaction features.

Change Service.addOrOverwriteEmbed algorithm that compared elements by
their id so that it now directly compares elements by reference equality.

Expand the service init test to include three different tests covering
initialization of multiple embeds with different element id
configurations (with id, without id*, with duplicated id*)

** These two tests will fail without the fix applied to service.ts

### CODE REVIEW

**Comment by ali-hamud** [comment]
Why to have such cases where multiple elements have the same id?

**Comment by oceantume** [comment]
While it is not recommended, re-using ID's is possible and that use-case was also broken by this bug. The reason why I added the three tests is to ensure that it now works properly regardless of the IDs of the elements. This test also verifies the number of "components" (elements) that are controlled by the API, something that wasn't really tested elsewhere because the Service instance is re-used and keeps references to elements that don't exist anymore.

**Comment by oceantume** [comment]
Any reason for not following through with this PR? Do you need me to change something? I'm hoping this can be published with the next minor version so I can use this library with React without having to add random ID's to my elements.

**Comment by kerosan** [comment]
in chrome browser when I try to load dashboard it loaded but without "fitting to with" or in "one column" and in console we have warning  `[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.`

**Comment by zoomcharts** [comment]
Hi Nick,

Adding our @support<mailto:support@zoomcharts.com> team to help you wth your request.


Kind regards,

[zoomcharts-logo-email-signature]


Katrina Barcevska
Customer Service specialist, ZoomCharts
+44 333 555 2505
info@zoomcharts.com

**Comment by VeBhairab** [comment]
Hi All, 
In the Power BI : I need the option fit to page functionality when user in full screen only but i didnt find any solution for it . 
My requirement is only, If user in full screen mode, user can use any option by which the data of pbi will fit in the screen without any vertical or horizontal scroll bar . I am using Angular7 with angular CLI.
Please let me know if anyone know it . 
Thanks .

**Comment by VeBhairab** [comment]
Hi All,
In the Power BI : I need the option fit to page functionality when user in full screen only but i didnt find any solution for it .
My requirement is only, If user in full screen mode, user can use any option by which the data of pbi will fit in the screen without any vertical or horizontal scroll bar . I am using Angular7 with angular CLI.
Please let me know if anyone know it .
Thanks .

**Comment by ali-hamud** [comment]
> Any reason for not following through with this PR? Do you need me to change something? I'm hoping this can be published with the next minor version so I can use this library with React without having to add random ID's to my elements.

@oceantume 
We want to accept and merge the PR.
We need to test the change in all the supported browsers.
We did not give this high priority between the other things. Thanks for understanding.

**Comment by parth-007** [comment]
For successful execution, 
What you can do is update the versions of packages in package.json file.

You can try this versions.
```
"gulp4-run-sequence": "^1.0.0",
"http-server": "^0.12.1",
"gulp-help-four": "^0.2.3",
"gulp": "^4.0.2",
"phantomjs-prebuilt": "^2.1.3", 
"ts-loader": "^6.2.2",
"typedoc": "^0.15.0"
"typescript": "^3.8.3"
"typings": "^1.3.2"
"webpack": "^4.42.1"2",
"webpack-stream": "^5.2.1",

```

**Pull request merged**
