### PR TITLE
Update util.ts

### PR DESCRIPTION
**Pull request by SanoLitch**
Fix undefined error in isRDLEmbed function. Raised exception on calling report page capture function.

### CODE REVIEW

**Comment by alexandermarston** [comment]
@ali-hamud any chance this could be reviewed?

**Review by ali-hamud — APPROVED** [review]

**Comment by ali-hamud** [comment]
> @ali-hamud any chance this could be reviewed?

@submarine-launched can you please merge this change after resolving the conflict in utils.ts?

**Comment by submarine-launched** [comment]
I merged the PR into our repository.
We will include this change in the next version of this library (powerbi-client npm package and Microsoft.PowerBI.JavaScript nuget package).
Thank you very much for your contribution.

**Comment by mpopova** [comment]
@submarine-launched, can you please tell me which day/month to expect the next version of the library?

**Pull request merged**
