### PR TITLE
Fix typescript error TS7051

### PR DESCRIPTION
**Pull request by RyZum**
Fix typescript error TS7051 : Parameter has a name but no type

### CODE REVIEW

**Comment by shep1987** [comment]
Same as 
https://github.com/Microsoft/PowerBI-JavaScript/pull/350

Not sure what has happened to master on this repository...

**Comment by ali-hamud** [comment]
We are removing the parameter at all as it's not needed.

**Comment by gwen1230** [comment]
@ali-hamud  When will this change be released ?

**Comment by ali-hamud** [comment]
Next release is on next Monday.

**Comment by ondrejkralik** [comment]
Can I ask which next Monday do you mean? Thanks.

**Comment by ali-hamud** [comment]
Fixed.

**Pull request closed without merging**
