### PR TITLE
Fix ts definition

### PR DESCRIPTION
**Pull request by shep1987**
Missing prop name

### CODE REVIEW

**Comment by gwen1230** [comment]
Please can you merge this and publish new version ?

**Comment by ali-hamud** [comment]
Thanks.

**Comment by ali-hamud** [comment]
> Please can you merge

We will publish a new version next week.

**Comment by gwen1230** [comment]
Thx !

**Comment by gwen1230** [comment]
Why this change is not included in 2.7.1 ? :(

**Pull request merged**
